name: Pure AWS EKS POC Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure-and-app:
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Log directly into AWS using your generated access keys
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -reconfigure


      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name poc-eks-cluster --region us-east-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s-deployment.yaml
          kubectl rollout status deployment/sample-nginx
